CREATE DATABASE choujiang;

CREATE TABLE t_user(
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(10) NOT NULL,
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = COMPACT;

INSERT INTO t_user (username,PASSWORD) VALUES('yuqinke1','123456');
INSERT INTO t_user (username,PASSWORD) VALUES('yuqinke2','123456');

CREATE TABLE t_award(
    id INT NOT NULL AUTO_INCREMENT,
    awardId INT NOT NULL,
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = COMPACT;